"""Project facts and supplied media."""
EXTRA_PROJECTS = {'en': [{'name': 'IFGF Cloud',
         'slug': 'ifgf-cloud',
         'url': 'https://cloud.ifgftaichung.dpdns.org/',
         'category': 'Private cloud · Infrastructure',
         'tagline': 'Shared files. Clear permissions. Fewer loose ends.',
         'description': 'Deployed private cloud storage on a mini PC, bringing file access and collaborative '
                        'documents into a centralized platform.',
         'tags': ['TrueNAS', 'Nextcloud', 'Collabora', 'Docker', 'Linux', 'RAID'],
         'case': ['Centralize organizational files and manage who can access them.',
                  'Configured RAID storage, user permissions, and file access controls; deployed Nextcloud '
                  'and Collabora with Docker.',
                  'Hands-on NAS deployment, Linux administration, and service integration.'],
         'icon': 'server'},
        {'name': 'Flyfitnity',
         'slug': 'flyfitnity',
         'category': 'Mobile · Hardware integration',
         'tagline': 'Real movement. Useful feedback.',
         'description': 'Developed a mobile application integrated with motion-sensing hardware for '
                        'real-time movement tracking and AI-assisted exercise recommendations.',
         'tags': ['Flutter', 'Raspberry Pi', 'Bluetooth', 'Python'],
         'case': ['Connect physical movement with feedback in a mobile application.',
                  'Collaborated on a Flutter application integrated with Raspberry Pi motion-sensing '
                  'hardware.',
                  'Received a TCA Honorable Award for the project.'],
         'repo': 'flyfitnity_bluetooth_connection',
         'icon': 'activity'},
        {'name': 'LearnAlgo',
         'slug': 'learnalgo',
         'videoThumbnail': 'https://i.ytimg.com/vi/ATqbLGN2ZBk/hqdefault.jpg',
         'category': 'Mobile · Research',
         'tagline': 'Making algorithms a little less abstract.',
         'description': 'Built the mobile learning platform used in my master’s thesis to study embodied and '
                        'situated approaches to algorithm learning.',
         'tags': ['Flutter', 'Firebase', 'Python'],
         'case': ['Explore how embodied and situated learning can support algorithm education.',
                  'Developed interactive learning flows and research data-collection mechanisms.',
                  'A working research application supporting the evaluation of learning approaches.'],
         'url': 'https://www.youtube.com/playlist?list=PLM97qnUGt3wg2bZ5MLHqysTbSy3SXrm1i',
         'linkLabel': 'Watch demos',
         'logo': 'learnalgo-logo',
         'videoEmbed': 'https://www.youtube-nocookie.com/embed/videoseries?list=PLM97qnUGt3wg2bZ5MLHqysTbSy3SXrm1i&autoplay=1',
         'media': [('learnalgo-situational', 1920, 1080, 'LearnAlgo · Scenario-based binary search'),
                   ('learnalgo-numbers', 1920, 1080, 'LearnAlgo · Numerical binary search')]},
        {'name': 'VirtualClass',
         'slug': 'virtualclass',
         'videoThumbnail': 'https://i.ytimg.com/vi/DH1pCYupwNM/hqdefault.jpg',
         'category': 'Android · Audio classification',
         'tagline': 'A teaching assistant with an ear for English.',
         'description': 'Led a four-person team building an English-teaching assistant app with cloud '
                        'services and a CNN-based audio classification module.',
         'tags': ['Kotlin', 'Firebase', 'Python', 'PyTorch', 'TorchAudio'],
         'case': ['Help teachers assess spoken English through a mobile teaching assistant.',
                  'Integrated Firebase services and an audio classification model in an Android application.',
                  'Received an Honorable Mention (佳作) at the 2021 university final-project exhibition.'],
         'logo': 'virtualclass-logo',
         'url': 'https://youtu.be/DH1pCYupwNM',
         'linkLabel': 'Watch demo',
         'videoEmbed': 'https://www.youtube-nocookie.com/embed/DH1pCYupwNM?autoplay=1',
         'media': [('virtualclass-poster', 1446, 2048, 'VirtualClass · Teacher and student workflows')]}],
 'zh': [{'name': 'IFGF Cloud',
         'slug': 'ifgf-cloud',
         'url': 'https://cloud.ifgftaichung.dpdns.org/',
         'category': '私有雲・基礎架構',
         'tagline': '檔案有歸處，權限有分寸。',
         'description': '使用 Mini PC 建置私有雲與集中式儲存平台，整合檔案存取與協作文件服務。',
         'tags': ['TrueNAS', 'Nextcloud', 'Collabora', 'Docker', 'Linux', 'RAID'],
         'case': ['集中管理組織檔案，並清楚設定各使用者的存取權限。',
                  '配置 RAID 儲存、使用者權限及檔案存取控制，透過 Docker 部署 Nextcloud 與 Collabora。',
                  '累積 NAS 部署、Linux 管理與服務整合的實務經驗。'],
         'icon': 'server'},
        {'name': 'Flyfitnity',
         'slug': 'flyfitnity',
         'category': '行動應用・軟硬體整合',
         'tagline': '讓每個動作，都有實用回饋。',
         'description': '開發整合動作感測硬體的行動應用，提供即時動作追蹤與 AI 輔助運動建議。',
         'tags': ['Flutter', 'Raspberry Pi', 'Bluetooth', 'Python'],
         'case': ['將實際運動與行動應用中的回饋連結。', '與團隊合作開發 Flutter 應用，整合 Raspberry Pi 動作感測硬體。', '專案榮獲人才循環大聯盟（TCA）佳作獎。'],
         'repo': 'flyfitnity_bluetooth_connection',
         'icon': 'activity'},
        {'name': 'LearnAlgo',
         'slug': 'learnalgo',
         'videoThumbnail': 'https://i.ytimg.com/vi/ATqbLGN2ZBk/hqdefault.jpg',
         'category': '行動應用・研究',
         'tagline': '讓演算法，不再那麼抽象。',
         'description': '開發碩士論文使用的行動學習平台，研究體現式與情境式學習在演算法教育中的應用。',
         'tags': ['Flutter', 'Firebase', 'Python'],
         'case': ['探索體現式與情境式學習如何支持演算法教育。', '設計並開發互動學習流程與研究資料蒐集機制。', '以可運作的研究系統，支持不同學習方法的評估。'],
         'url': 'https://www.youtube.com/playlist?list=PLM97qnUGt3wg2bZ5MLHqysTbSy3SXrm1i',
         'linkLabel': '觀看示範影片',
         'logo': 'learnalgo-logo',
         'videoEmbed': 'https://www.youtube-nocookie.com/embed/videoseries?list=PLM97qnUGt3wg2bZ5MLHqysTbSy3SXrm1i&autoplay=1',
         'media': [('learnalgo-situational', 1920, 1080, 'LearnAlgo・情境式二分搜尋'),
                   ('learnalgo-numbers', 1920, 1080, 'LearnAlgo・數字二分搜尋')]},
        {'name': 'VirtualClass',
         'slug': 'virtualclass',
         'videoThumbnail': 'https://i.ytimg.com/vi/DH1pCYupwNM/hqdefault.jpg',
         'category': 'Android・音訊分類',
         'tagline': '讓教學助理，也能「聽」懂英語。',
         'description': '帶領四人團隊開發教師英語教學輔助應用，整合雲端服務與 CNN 音訊分類模組。',
         'tags': ['Kotlin', 'Firebase', 'Python', 'PyTorch', 'TorchAudio'],
         'case': ['以行動教學助理，協助教師進行英語口說評量。', '於 Android 應用中整合 Firebase 雲端服務與音訊分類模型。', '榮獲 2021 年大學專題成果展佳作獎。'],
         'logo': 'virtualclass-logo',
         'url': 'https://youtu.be/DH1pCYupwNM',
         'linkLabel': '觀看示範影片',
         'videoEmbed': 'https://www.youtube-nocookie.com/embed/DH1pCYupwNM?autoplay=1',
         'media': [('virtualclass-poster', 1446, 2048, 'VirtualClass・教師與學生操作流程')]}]}
